import type { CandidateAction } from "./types";

export const sampleCandidates: CandidateAction[] = [
  {
    id: "research-chatgpt",
    groupKey: "cursor-award-research",
    title: "ハッカソンの受賞プロジェクト事例を調べる",
    type: "Research",
    statusHint: "Ready",
    confidence: 0.91,
    actionable: true,
    owner: "あなた",
    executor: "Demo Codex Research",
    effect: "出典付きの調査メモを作成します。外部公開はしません。",
    evidence: {
      id: "ev-research-chatgpt",
      sourceKind: "ChatGPT",
      sourceTitle: "ハッカソンの勝ち筋を相談",
      occurredAt: "今日 09:42",
      quote: "ハッカソンの過去の受賞例を調べて、デモの見せ方を参考にしたい。",
      strength: "intent",
    },
  },
  {
    id: "research-meeting",
    groupKey: "cursor-award-research",
    title: "ハッカソンの受賞例を5件調べて月曜までに共有する",
    type: "Research",
    statusHint: "Ready",
    confidence: 0.97,
    actionable: true,
    owner: "あなた",
    due: "7月20日（月）",
    executor: "Demo Codex Research",
    effect: "5件の出典付き調査メモを作成します。外部公開はしません。",
    evidence: {
      id: "ev-research-meeting",
      sourceKind: "Meeting",
      sourceTitle: "Build Week 作戦会議",
      occurredAt: "今日 11:18",
      quote: "ハッカソンの受賞例を5件、月曜までにまとめておこう。",
      strength: "explicit",
    },
  },
  {
    id: "calendar-meeting",
    groupKey: "retro-calendar",
    title: "Build Weekの振り返り時間を確保する",
    type: "Calendar hold",
    statusHint: "Needs input",
    confidence: 0.88,
    actionable: true,
    owner: "あなた",
    executor: "Demo Calendar",
    effect: "自分用の仮予定を作成します。招待や通知は送りません。",
    missingField: "開催日時",
    inputOptions: ["月曜 10:00–10:30", "月曜 16:00–16:30", "火曜 11:00–11:30"],
    evidence: {
      id: "ev-calendar-meeting",
      sourceKind: "Meeting",
      sourceTitle: "Build Week 作戦会議",
      occurredAt: "今日 11:26",
      quote: "終わったら30分だけ振り返りの時間を取ろう。日時はあとで決める。",
      strength: "explicit",
    },
  },
  {
    id: "email-chatgpt",
    groupKey: "yuki-demo-followup",
    title: "YukiさんへデモURLを共有する",
    type: "Email draft",
    statusHint: "Ready",
    confidence: 0.86,
    actionable: true,
    owner: "あなた",
    executor: "Demo Gmail",
    effect: "メール下書きを作成します。送信はしません。",
    evidence: {
      id: "ev-email-chatgpt",
      sourceKind: "ChatGPT",
      sourceTitle: "デモ説明文の推敲",
      occurredAt: "今日 12:04",
      quote: "サイトができたらYukiさんにURLを共有するのを忘れないようにしたい。",
      strength: "intent",
    },
  },
  {
    id: "email-meeting",
    groupKey: "yuki-demo-followup",
    title: "YukiさんへデモURLと試してほしい点を送る",
    type: "Email draft",
    statusHint: "Ready",
    confidence: 0.94,
    actionable: true,
    owner: "あなた",
    due: "デプロイ後",
    executor: "Demo Gmail",
    effect: "URLと確認ポイントを含むメール下書きを作成します。送信はしません。",
    evidence: {
      id: "ev-email-meeting",
      sourceKind: "Meeting",
      sourceTitle: "Build Week 作戦会議",
      occurredAt: "今日 11:31",
      quote: "デプロイ後、YukiさんにURLと、特にスワイプを試してほしいって送ろう。",
      strength: "explicit",
    },
  },
  {
    id: "codex-completed",
    groupKey: "keyboard-test",
    title: "カードのキーボード操作テストを追加する",
    type: "Codex task",
    statusHint: "Completed",
    confidence: 0.98,
    actionable: true,
    owner: "あなた",
    executor: "Codex",
    effect: "テストを追加します。",
    evidence: {
      id: "ev-codex-completed",
      sourceKind: "Codex",
      sourceTitle: "Action Deck accessibility",
      occurredAt: "今日 12:36",
      quote: "左右・上矢印とEnterの操作テストを追加し、全テストが成功しました。",
      strength: "execution",
    },
  },
  {
    id: "low-confidence-wish",
    groupKey: "future-redesign",
    title: "いつかトップ画面を全面的に作り直す",
    type: "Codex task",
    statusHint: "Ready",
    confidence: 0.38,
    actionable: false,
    owner: "不明",
    executor: "Codex",
    effect: "コードを変更します。",
    evidence: {
      id: "ev-low-confidence",
      sourceKind: "ChatGPT",
      sourceTitle: "雑談メモ",
      occurredAt: "昨日 18:10",
      quote: "いつかトップ画面を全部作り直すのも面白いかも。",
      strength: "intent",
    },
  },
];

export const sampleSourceNames = [
  "Build Week 作戦会議",
  "ハッカソンの勝ち筋を相談",
  "デモ説明文の推敲",
  "Action Deck accessibility",
  "雑談メモ",
];
